image: maven:latest
pipelines:
  default:
    - step:
        name: "Build"
        script:
          - mvn install
          - cp $WAR_PATH App.war
        artifacts:
          - App.war
    - step:
        name: "Undeploy"
        script:
          - curl "https://$TOMCAT_USER:$TOMCAT_PASSWORD@$TOMCAT_SERVER:443/manager/text/undeploy?path=$APP_PATH"
    - step:
        name: "Deploy"
        deployment: production
        script:
          - curl --upload-file App.war "https://$TOMCAT_USER:$TOMCAT_PASSWORD@$TOMCAT_SERVER:443/manager/text/deploy?path=$APP_PATH"